### ISSUE TITLE
Determine the historical population to create the base population

### ISSUE THREAD

**Issue by bkenayati** [gaynorr/AlphaSimR#19]
Hi Dear friends
I am working on a selection strategy on a species of forest trees. In this specie the LD is about 0.25 in 2500 bp windows. Its historical population has also not been studied. The average of chromosomes recombination in this specie is 16×10-8. The simulation experiences by the Runmacs function has shown that LD is more affected by the effective population size than the recombination rate. Tree parameters BaseNe, GenerationsAgo and Ne affected LD according following command.
BaseNe = 500
AncientNe = tibble(GenerationsAgo = c(100, 500, 1000,  5000, 10000, 100000, 1000000),Ne = c(100, 250, 1000, 10000, 50000, 250000,  500000))

Please tell me how they should be changed (BaseNe, GenerationsAgo and Ne) for this function so that I can reach this ratio of LD.
Thanks a lot

**Comment by gregorgorjanc** [comment]
Hi @bkenayati! Thanks for the question. This is quite tricky, but we find that if you use reasonable past Ne (see what we have implemented in `runMacs()`!) then we get reasonable genome summaries. Furthermore, note that this is only a starting point of a simulation, and that you would ideally add some burn-in phase that will induce further linkage-disequilibrium, due to selection, as well as relatedness in your breeding programme - also contributing to the linkage-disequilibrium. You will have to find yourself how exactly you should change the Ne and time values;)
