### ISSUE TITLE
Turn on mutations by default when generating new individuals?

### ISSUE THREAD

**Issue by gregorgorjanc** [gaynorr/AlphaSimR#36]
When we create new individuals we generally always recombine parental genomes.

Given that mutation is also "always" happening, should we not turn it on alongside recombination too?

**Comment by gaynorr** [comment]
I wouldn't do that with the current mutation model. It doesn't play well with recombination tracking, because I don't have a built-in mutation tracking system. You also probably want to allow for adding new polymorphic loci. The current mutation model just mutates existing loci. Due to these limitations, I have left mutation as a separate function for the time being. At the moment, I don't have any serious plans for expanding it.

**Comment by gregorgorjanc** [comment]
Fair enough! Best to revise this with tree sequence down the road.
