### ISSUE TITLE
writePlink doesn't work when chromosomes with different lengths are simulated

### ISSUE THREAD

**Issue by alanaselli** [gaynorr/AlphaSimR#58]
I simulated chromosomes with different lengths, and I wasn't able to use the writePlink function. I tried exporting all chromosomes using a singular chromosome length, but it still wouldn't work, because the data was simulated with different chromosome lengths. It would be an immense improvement if writePlink worked with different chromosome lengths!
The package is excellent so far, thanks a lot for providing this tool for us.

EDIT: grammar

**Comment by gaynorr** [comment]
Thanks for bringing this to my attention. I'll try to look at it tomorrow.

**Comment by gaynorr** [comment]
@alanaselli, sorry it took me a while to get back to you. I ended up rewriting this function, because there were a couple of bugs that were easier to resolve with a rewrite since it wasn't a function I originally wrote myself. The newest version can be tested using the devel branch. `devtools::install_github(repo="gaynorr/AlphaSimR@devel")` 

If you try it, let me know how it works for you as I'm still doing some testing before committing this version to CRAN.

**Comment by alanaselli** [comment]
@gaynorr I'm sorry it took me so long to test the function. The only problem I could find is that it uses the segregating sites instead of the specified SNP chip. It works fine with QTL. Thanks for your time!
