### ISSUE TITLE
Are correlation/covariance parameters stored in the SP object?

### ISSUE THREAD

**Issue by poca87** [gaynorr/AlphaSimR#63]
Imagine this simulation:

```
library(AlphaSimR)
founderGenomes = runMacs(nInd = 100,
                         nChr = 10,
                         segSites = 100)

SP = SimParam$new(founderGenomes)

# Define the traits
means = c(100, 100)
vars = c(100, 100)
cors = matrix(data = c( 1.0, -0.5,
                       -0.5,  1.0),
                byrow = TRUE, nrow = 2, ncol = 2)
SP$addTraitA(nQtlPerChr = 50, mean = means, var = vars, corA = cors)
```

How can I see variance parameters used in the simulation? Well we have them in the `SP`

```
> SP$varA
[1] 1 2
> SP$varG
[1] 1 2
```

But, I can't seem to find correlations (or covariances) at all. I know we can get them for each population object, but would be good to store them also in the SP.

**Comment by gaynorr** [comment]
No, they aren't stored for the QTL effects. They get used to generate the effects and are then forgotten. The varA and varG values stored in SimParams are really just for the h2 and H2 calculations in `setPheno`. The covariances are stored for varE, because it gets used to generate new residual errors.

**Comment by gregorgorjanc** [comment]
I think it would make sense to store the correlation matrix - for completeness.
